[sc-11899] Remove Adapter object from templates
SGNL-ai/catalog-sgnl-templates pull request #16
Opened 2023-08-23 17:42 UTC by nholbrook

- Moves the `adapter.config` field to `adapterConfig`
- Moves the `adapter.auth` field to `auth`
- Adds a `type` field
- Removes the `adapter` object

2023-08-23 17:57 UTC, nholbrook commented
cc @ivanfong for the format changes

2023-08-24 00:21 UTC, shash-sgnl requested changes

2023-08-24 00:21 UTC, shash-sgnl commented on azure-ad.sgnl.yaml
> +adapterConfig: "ewoJInZlcnNpb24iOiAxLAoJImNvbmZpZyI6IHsKICAgICAgICAgICAgICAgICJmaWx0ZXJzIjoge30sCgkJInJlcXVlc3RUaW1lb3V0IjogIjEwcyIsCgkJImF6dXJlYWQiOiB7CiAgICAgICAgICAgICAgICAgICAgImFwaVZlcnNpb24iOiA
Do you mind adding the following decoded json as a single-line comment as an example of what it looks like? 
```
{ "version": 1, "config": { "filters": {}, "requestTimeout": "10s",  "azuread": { "apiVersion": "v1.0" } } }
```

2023-08-24 00:21 UTC, shash-sgnl commented on okta.sgnl.yaml
> +adapterConfig: "ewogICAgInZlcnNpb24iOiAxLAogICAgImNvbmZpZyI6IHsKICAgICAgICAicmVxdWVzdFRpbWVvdXQiOiAiMTBzIiwKICAgICAgICAib2t0YSI6IHsKICAgICAgICAgICAgImFwaVZlcnNpb24iOiAidjEiCiAgICAgICAgfQogICAgfQp9"
Please add the following as a single-line comment here as an example of what it looks like:
```
{
    "version": 1,
    "config": {
        "requestTimeout": "10s",
        "okta": {
            "apiVersion": "v1"
        }
    }
}
```

2023-08-24 00:21 UTC, shash-sgnl commented on salesforce.sgnl.yaml
> +adapterConfig: "ewoJInZlcnNpb24iOiAxLAoJImNvbmZpZyI6IHsKCQkicmVxdWVzdFRpbWVvdXQiOiAiMTBzIiwKCQkic2FsZXNmb3JjZSI6IHsiYXBpVmVyc2lvbiI6IjU2LjAifQoJfQp9"
Please add the following as a single-line comment here as an example of what it looks like:
```
{
	"version": 1,
	"config": {
		"requestTimeout": "10s",
		"salesforce": {"apiVersion":"56.0"}
	}
}
```

2023-08-24 00:21 UTC, shash-sgnl commented on servicenow.sgnl.yaml
> +adapterConfig: "CnsKCSJ2ZXJzaW9uIjogMSwKCSJjb25maWciOiB7CgkJInJlcXVlc3RUaW1lb3V0IjogIjEwcyIsCgkJInNlcnZpY2Vub3ciOiB7fQoJfQp9Cg=="
Please add the following as a single-line comment here as an example of what it looks like: 
```
{
	"version": 1,
	"config": {
		"requestTimeout": "10s",
		"servicenow": {}
	}
}
```

2023-08-24 22:54 UTC, shash-sgnl approved these changes

2023-08-24 22:54 UTC, merged