[sc-8732] Add Curity template
SGNL-ai/catalog-sgnl-templates pull request #31
Opened 2023-10-26 17:47 UTC by r-rakshith

This PR adds a Curity template that contains the `User` entity and it's child entities (emails, phonenumbers.....) from the SCIM template as the base. This template uses the `SCIM2.0-1.0.0` adapter.

2023-10-27 19:05 UTC, r-rakshith commented
https://app.shortcut.com/sgnl/story/8732

2023-11-02 17:02 UTC, nholbrook requested changes

2023-11-02 19:58 UTC, r-rakshith commented on curity.sgnl.yaml
> +# This must match the list of supportedAuthMechanisms specified on the Adapter.
Updated all templates.

2023-11-02 19:59 UTC, r-rakshith commented on curity.sgnl.yaml
> +    pagesOrderedById: false
Removed.

2023-11-03 21:16 UTC, nholbrook approved these changes

2023-11-03 21:19 UTC, merged