[sc-25700] Add catalog for AWS
SGNL-ai/catalog-sgnl-templates pull request #65
Opened 2024-06-21 19:25 UTC by Mohitp98

#### This is an initial version of the `AWS` catalog: 

**Shortcut story**

[sc-25700](https://app.shortcut.com/sgnl/story/25700/aws-iam-as-an-sor)

2024-07-17 18:09 UTC, r-rakshith requested changes

2024-07-17 18:09 UTC, r-rakshith commented on aws.sgnl.yaml
> +    description: Role entity in AWS
Please update all entity descriptions to match

```
{{Entity}} represents a {{AWS Resource (AWS IAM Role)}}
```

2024-07-19 06:20 UTC, Mohitp98 commented
### Catalog testing

- Able to ingest all the entities

    ![image](https://github.com/user-attachments/assets/c43cb8c6-5376-41fb-93ec-92ec4a9cbefc)

2024-07-19 06:28 UTC, r-rakshith approved these changes
LGTM overall!

2024-07-19 13:00 UTC, merged